### ISSUE TITLE
Documentation is stale

### ISSUE THREAD

**Issue by xstos** [OfficeDev/Outlook-Add-in-SSO#10]
Is there an updated version of the app registration instructions [here](https://github.com/OfficeDev/outlook-add-in-attachments-demo) ? The portal has been absorbed by azure and looks completely different and I'm having trouble even getting the sample to work. Are there any tools to just autoconfigure everything automatically? I couldn't care less about security I just want to create a test addin like I used to in VSTO-land and try stuff out.

**Comment by ElizabethSamuel-MSFT** [comment]
@xstos Thanks for pointing this out.

In the meantime, consider trying the [quick start](https://docs.microsoft.com/outlook/add-ins/quick-start?tabs=yeomangenerator) or [tutorial](https://docs.microsoft.com/outlook/add-ins/addin-tutorial) in the Outlook developer documentation.

Thanks.

**Comment by ghost** [comment]
Any update on this?

**Comment by davidchesnut** [comment]
We've updated and moved the Outlook add-in SSO sample to the PnP repo at: https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Outlook-Add-in-SSO

The registration instructions should be up to date, but please let us know if we missed anything.
Thanks!
