### ISSUE TITLE
External SSO Authentication

### ISSUE THREAD

**Issue by elthombre** [OfficeDev/Outlook-Add-in-SSO#19]
Is there any good reason to embed an add-in within the website being used for authentication (for both email & password as well as SSO)? 

For example, in my case, we have a large corporate website which, presently, returns an HTTPOnly cookie. There are some that believe embedding the SPA add-in within the ASP.Net solution is the way to go in order to get around some of the issues pertaining to the iFrame.

Does this make good sense to you? I ask because it's my understanding that 1) not only should such projects not be tightly coupled, 2) the way these add-ins are setup, they are meant to accommodate external authentication. It is my understanding that extending an API to accommodate an add-in login aligns with industry standards, etc.

**Comment by davidchesnut** [comment]
Hi @elthombre,

This question is around general security and Azure Active Directory security practices. We recommend taking a look at [Authentication flows and application scenarios](https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-flows-app-scenarios).

Also a good place to ask this question would be on the [Azure Active Directory Q&A site](https://docs.microsoft.com/en-us/answers/topics/azure-active-directory.html). 

Hope this helps,
David

**Comment by elthombre** [comment]
You're assuming Azure is in play which it wasn't.

**Comment by davidchesnut** [comment]
Sorry @elthombre, I misunderstood,

In this case you cannot use SSO with Office. Office SSO (calling the getAccessToken API) requires your add-in to be registered with Azure AD. You would have to configure your Azure registration using the steps in [Enable single sign-on for Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins).

Cheers,
David

**Comment by elthombre** [comment]
I believe there was a 3rd party library in play for SSO / SAML, etc.

**Comment by davidchesnut** [comment]
Closing as this sample has moved to: https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Outlook-Add-in-SSO
