### ISSUE TITLE
OWA and iFrame

### ISSUE THREAD

**Issue by elthombre** [OfficeDev/Outlook-Add-in-SSO#20]
Is there a way to update the web.config of an Outlook for web add-in to prevent the "... cannot be displayed in a frame" error?

Thanks

**Comment by davidchesnut** [comment]
Hi @elthombre,

Are you seeing this behavior with this sample when the task pane is loaded? Or is this happening when the dialog box is to be displayed for authentication?

Thanks!
David

**Comment by elthombre** [comment]
Not on this project any longer. Sorry.
