### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by andre-claesson** [OfficeDev/Outlook-Add-in-SSO#21]
Shouldn't this be updated to ASP.NET Core? According to Microsoft docs, new development should use Core and I think most people use these samples for new development.

**Comment by davidchesnut** [comment]
Hi @andre-claesson,

We're in the process of updating and moving these SSO samples to the PnP repo. The updated Outlook add-in SSO sample is at https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Outlook-Add-in-SSO.

The ASP.NET web server is updated in the project solution, but it is not ASP.NET Core. We're not really focused on the type of web server. The samples or more about showing how to interact with Office to get the SSO token and use a fallback dialog.

Thanks!
David

**Comment by andre-claesson** [comment]
Thanks. I ended up porting it myself to Core. Wasn't too difficult.
