### ISSUE TITLE
getAccessTokenAsync returns error 13007

### ISSUE THREAD

**Issue by mvpkenlin** [OfficeDev/Outlook-Add-in-SSO#3]
I move the application to Azure Web App. I then have done the app registration, apply the AppID and the reply URL to the app config. I then grant user consent to the add-in. 

But when I run it in Outlook, it returns 13007 with message "An unexpected error occurred on the server. 

With the same code, I also register another one on localhost, it works. Why?

**Comment by jasonjoh** [comment]
Is the URL to your app on Azure a `*.azurewebsites.net` address?

**Comment by mvpkenlin** [comment]
yes, I found that it is under "Azure AD only applications" which I cannot add the pre-authorized applications. 

So at the same time, I add DNS record as "oai.{myCompanyDomain}.com" and point it to "{myapp}.azurewebsites.net". I then added another registration under "Converged applications" with the returnURL to be "oai.{myCompanyDomain}.com".

Now I have 3 duplicated manifest file, html file, js file, and config files so that each set of them are pointing to "localhost:port", "{myapp}.azurewebsites.net" and "oai.{myCompanyDomain}.com" with their corresponding AppID and returnURL. 

Both are returning 13007 when calling getAccessTokenAsync except it works on localhost one.

**Comment by jasonjoh** [comment]
Did you provide consent for your user with the new registration?

**Comment by mvpkenlin** [comment]
Yes, I provided consent to myself and test it after each time I have modified anything from the application registration portal in IE11 and Edge
```
https://login.microsoftonline.com/common/oauth2/authorize?client_id={App ID}&state=12345&response_type=code
```

**Comment by jasonjoh** [comment]
Do you have a valid, trusted cert for HTTPS on your oai.mycompanydomain.com domain?

**Comment by mvpkenlin** [comment]
Yes
![https_cert](https://user-images.githubusercontent.com/20411183/37012590-714e4466-2130-11e8-83a9-9a1f743c5f3f.png)

**Comment by jasonjoh** [comment]
Can you try this in Outlook Web app at https://outlook.office.com? Do you get the same error?

**Comment by sebastianbouckaert** [comment]
Were you able to solve this because I have the same issue...

**Comment by mvpkenlin** [comment]
@sebastianbouckaert No, I don't know how to resolve it.

@jasonjoh Tried. Still get the same error.

**Comment by sebastianbouckaert** [comment]
@mvpkenlin  We called for Micrrosoft help to deal with this issue because I spend 3 days ont his with the same result, I'll keep you posted

**Comment by sebastianbouckaert** [comment]
@mvpkenlin they are still investigating 🤗

**Comment by jasonjoh** [comment]
I had some similar issues, so I wanted to share some things I've figured out :)

- If you're doing this in OWA, then we need to add an additional app ID under **Pre-authorized applications** in the app registration. OWA uses a different app ID than desktop Outlook. You need to also add bc59ab01-8403-45c6-8796-ac3ef710b3e3.

    ![image](https://user-images.githubusercontent.com/8966342/38378309-40c34294-38cb-11e8-9c6e-3377f4e0e4ff.png)

- Make sure that you've got the up-to-date consent by going to this URL in your browser (note the addition of the `prompt=consent` parameter: `https://login.microsoftonline.com/common/oauth2/authorize?client_id={your-app-id}&state=12345&response_type=code&prompt=consent`. This will force Azure to refresh your recorded consent to pick up any changes to the app registration.

Doing these two steps got me past 13007 and 13005 errors in OWA and Desktop Outlook.

**Comment by mvpkenlin** [comment]
@jasonjoh My outlook addin app is hosted under Azure App Service and it becomes an "Azure AD Only application" type under application registration. This type is difference from the "converged application" type. And there is no option to add "pre-authorized applications". 

The "Azure AD Only Application" type can only edit the manifest of the registration. But the supported tags are difference from the supported tags under "converged application". I tried to copy the tags on "pre-authorized applications" into the manifest for "Azure AD Only Application" and it stops me save it as the modified xml has unsupported tags.

As I said in the first post, I registered new app under "converged App" type for localhost (development env) and it works without any problem. But as the addin is hosting under "Azure App Service" and the app is automatically created under the app reg page. Same code and it generate errors.

![appreg](https://user-images.githubusercontent.com/20411183/38970850-56dcca84-4387-11e8-9619-606a253ca8dd.png)

**Comment by jasonjoh** [comment]
Oh, yeah, that's your problem. Use the registration created in apps.dev.microsoft.com. You don't have to use the app ID/secret that Azure gives you.

Basically deploy your add-in to Azure, then create your own app registration at apps.dev.microsoft.com (which will create a converged registration), giving it the proper callback URLs and pre-auth applications.
