### ISSUE TITLE
Fail to deploy this add in to Office 365

### ISSUE THREAD

**Issue by tuandomvn** [OfficeDev/Outlook-Add-in-SSO#4]
I am using this sample  to deploy to my Azure. I followed the instruction and I could run the project successfully in local PC. However, I failed to upload this sample to my tenant.

The steps I did are as below:

- Deploy the project to azure website.
- In the manifest file, I just replace all tags with ~remoteAppUrl with my new uploaded website URL (https://testxxxx.azurewebsites.net)
- Then I go to my Outlook online, select Manage Add ins menu and upload my manifest file. But it failed.
- I tried to reproduce it why it failed, I realized that it failed in Urls/Url tag. If I keep the Urls point to my local PC then it works. If I point them to azure website URL, it didn't.

It worked with these lines:

<bt:Url id="functionFile" DefaultValue="https://localhost:44349/Functions/FunctionFile.html"/>
<bt:Url id="messageReadTaskPaneUrl" DefaultValue="https://localhost:44349/MessageRead.html"/>

and failed when I replaced the URLs

<bt:Url id="functionFile" DefaultValue="https://testoladd.azurewebsites.net/Functions/FunctionFile.html"/>
<bt:Url id="messageReadTaskPaneUrl" DefaultValue="https://testoladd.azurewebsites.net/MessageRead.html"/>

Please advise me in this situation.

**Comment by davidchesnut** [comment]
Closing as updates over time have likely fixed this. The sample has moved to: https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Outlook-Add-in-SSO
