### ISSUE TITLE
how to directly save the attachment to other locations when the attachment is uploading

### ISSUE THREAD

**Issue by qquiuc** [OfficeDev/Outlook-Add-in-SSO#5]

**Comment by qquiuc** [comment]
Hi team, i'm working with outlook web add-in now, 
I have such a request, customer wants to have the function to upload the file directly to other locations before they uploaded to the outlook, then leave a link in the email body.
Is there any way to implement this function?
Thanks 
@yinaa @dmahugh @dclaux @tony-zhu @robmhoward

**Comment by davidchesnut** [comment]
Closing as sample has moved to: https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Outlook-Add-in-SSO
