### ISSUE TITLE
Is there a way to get the Onedrive/SharePoint token without prompting for credentials

### ISSUE THREAD

**Issue by venkatkonjeti** [OfficeDev/Outlook-Add-in-SSO#6]
I am able get the Graph token but wondering is there a way to get the Onedrive/SharePoint token without prompting for credentials to achieve missing features in Graph API.

**Comment by davidchesnut** [comment]
Closing as sample has now moved to: https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Outlook-Add-in-SSO
