### ISSUE TITLE
Error building sample after updating MailAppVersionOverridesV1_1.xsd file

### ISSUE THREAD

**Issue by JoeVice** [OfficeDev/Outlook-Add-in-SSO#7]
Using VS2017 Professional (15.8.6)

Configured and installed everything like readme says. Then got a build error (WebApplicationInfo invalid), saw you already described workaround. But after updating the file next ->

Build error "The http://schemas.microsoft.com/office/mailappversionoverrides/1.1:VersionOverrides-Element was not declared." after updating the MailAppVersionOverridesV1_1.xsd file with https://raw.githubusercontent.com/OfficeDev/outlook-add-in-attachments-demo/master/manifest-schema-fix/MailAppVersionOverridesV1_1.xsd  (previous error: WebApplicationInfo invalid ...) 

Calling the schema in browser tells me "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." Meh.

Would you advise? 

Thanks in advance ;)

**Comment by davidchesnut** [comment]
There's a known issue around this which is now documented in the readme "Troubleshooting manifest issues". The sample is now moved to: https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Outlook-Add-in-SSO
