### ISSUE TITLE
Link to https://unpkg.com/core-js/client/core.min.js in MessageRead.html is broken

### ISSUE THREAD

**Issue by CameronDwyer** [OfficeDev/Outlook-Add-in-SSO#8]
<script src="https://unpkg.com/core-js/client/core.min.js" type="text/javascript"></script>

I was able to get the sample working using this version specific URL instead.
https://unpkg.com/core-js@2.6.1/client/core.min.js

**Comment by davidchesnut** [comment]
Should be fixed now. This sample was recently moved to: https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Outlook-Add-in-SSO
